# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Futurehome
version: "0.0.8"
slug: futurehome
description: Local Futurehome Smarthub integration
url: "https://github.com/adrianjagielak/home-assistant-futurehome"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

services:
  - "mqtt:need"

options:
  hub_ip: ""
  username: ""
  password: ""

schema:
  hub_ip: "str?"
  username: "str"
  password: "str"

image: "ghcr.io/adrianjagielak/{arch}-home-assistant-futurehome"
