# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Futurehome
version: "0.1.7"
slug: futurehome
description: Local Futurehome Smarthub integration
url: "https://github.com/adrianjagielak/home-assistant-futurehome"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

services:
  - "mqtt:need"

options:
  hub_ip: ""
  username: ""
  password: ""
  demo_mode: false
  show_debug_log: false

schema:
  hub_ip: "str?"
  username: "str?"
  password: "str?"
  demo_mode: "bool?"
  show_debug_log: "bool?"

image: "ghcr.io/adrianjagielak/{arch}-home-assistant-futurehome"
